name: Run TestCafe tests
on:
  - push
jobs:
  build:
    name: Install Node and launch TestCafe tests in Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: chrome tests --concurrency ${{ steps.cpu-cores.outputs.count }}
